# Data Cleaning

In [2]:
import pandas as pd
data = pd.read_excel('Customer Perception on Electric Vehicles_May 22, 2021_17.54.xlsx')  # 或xls
pd.set_option('display.max_columns', None)  # 不隐藏列
data.head()

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,RecipientFirstName,RecipientEmail,ExternalReference,LocationLatitude,LocationLongitude,DistributionChannel,UserLanguage,Q1_1,Q1_2,Q1_3,Q1_4,Q1_5,Q1_6,Q1_7,Q3_1,Q3_2,Q3_3,Q3_4,Q3_5,Q3_6,Q3_7,Q4_1,Q4_2,Q4_3,Q4_4,Q4_5,Q4_6,Q4_7,Q5_1,Q5_2,Q5_3,Q5_4,Q5_5,Q5_6,Q5_7,Q6,Q7,Q8,Q9,Q10
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,Recipient First Name,Recipient Email,External Data Reference,Location Latitude,Location Longitude,Distribution Channel,User Language,The purpose of this survey is to analyse custo...,The purpose of this survey is to analyse custo...,The purpose of this survey is to analyse custo...,The purpose of this survey is to analyse custo...,The purpose of this survey is to analyse custo...,The purpose of this survey is to analyse custo...,The purpose of this survey is to analyse custo...,BMW - Please rate the statements from 1 (Extre...,BMW - Please rate the statements from 1 (Extre...,BMW - Please rate the statements from 1 (Extre...,BMW - Please rate the statements from 1 (Extre...,BMW - Please rate the statements from 1 (Extre...,BMW - Please rate the statements from 1 (Extre...,BMW - Please rate the statements from 1 (Extre...,Hyundai - Please rate the statements from 1 (E...,Hyundai - Please rate the statements from 1 (E...,Hyundai - Please rate the statements from 1 (E...,Hyundai - Please rate the statements from 1 (E...,Hyundai - Please rate the statements from 1 (E...,Hyundai - Please rate the statements from 1 (E...,Hyundai - Please rate the statements from 1 (E...,Audi - Please rate the statements from 1 (Extr...,Audi - Please rate the statements from 1 (Extr...,Audi - Please rate the statements from 1 (Extr...,Audi - Please rate the statements from 1 (Extr...,Audi - Please rate the statements from 1 (Extr...,Audi - Please rate the statements from 1 (Extr...,Audi - Please rate the statements from 1 (Extr...,What's your gender?,What's your age group?,What's your level of education?,What's your annual income level? (in AUD),Do you own a car?
1,2021-05-20 16:40:55,2021-05-20 16:43:24,IP Address,49.180.248.16,100,149,True,2021-05-20 16:43:24.837000,R_1BNLvUyfQrs0zoR,NaN,NaN,NaN,NaN,-33.856293,151.212189,anonymous,EN,7,8,1 - Extremely Disagree,9,1 - Extremely Disagree,3,5 - I'm not sure,8,5 - I'm not sure,8,6,9,7,9,3,5 - I'm not sure,5 - I'm not sure,3,5 - I'm not sure,6,3,7,4,8,7,9,6,5 - I'm not sure,Female,18-25,Postgraduate,"Below $18,000",No
2,2021-05-20 16:57:30,2021-05-20 16:58:58,IP Address,43.225.62.66,100,88,True,2021-05-20 16:58:58.913000,R_241pEiX5GGbjl2Q,NaN,NaN,NaN,NaN,-35.269699,149.137512,anonymous,EN,6,7,8,9,8,8,10 - Extremely Agree,10 - Extremely Agree,5 - I'm not sure,7,4,6,8,8,1 - Extremely Disagree,1 - Extremely Disagree,3,1 - Extremely Disagree,4,4,3,8,3,3,6,7,9,8,Male,36-45,Postgraduate,"Above $110,000",Yes
3,2021-05-20 17:02:42,2021-05-20 17:05:56,IP Address,103.192.227.226,100,193,True,2021-05-20 17:05:56.532000,R_12S8jTeh77IdKY5,NaN,NaN,NaN,NaN,22.257797,114.16571,anonymous,EN,4,8,3,8,1 - Extremely Disagree,5 - I'm not sure,5 - I'm not sure,6,8,9,8,9,5 - I'm not sure,8,3,6,8,6,8,5 - I'm not sure,6,5 - I'm not sure,6,7,7,8,5 - I'm not sure,7,Female,26-35,Undergraduate,"$30,000-$50,000",Yes
4,2021-05-20 17:04:25,2021-05-20 17:06:15,IP Address,1.159.46.246,100,109,True,2021-05-20 17:06:15.260000,R_5szq28NGXKsyryp,NaN,NaN,NaN,NaN,-37.908798,144.9953,anonymous,EN,4,9,7,6,9,6,9,6,5 - I'm not sure,5 - I'm not sure,3,7,8,7,3,4,4,6,7,7,2,9,4,4,5 - I'm not sure,6,7,6,Male,36-45,TAFE,"Above $110,000",Yes

In [3]:
data.shape

(42, 50)

In [4]:
data.drop(data.index[0], inplace=True)
data.head()

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,RecipientFirstName,RecipientEmail,ExternalReference,LocationLatitude,LocationLongitude,DistributionChannel,UserLanguage,Q1_1,Q1_2,Q1_3,Q1_4,Q1_5,Q1_6,Q1_7,Q3_1,Q3_2,Q3_3,Q3_4,Q3_5,Q3_6,Q3_7,Q4_1,Q4_2,Q4_3,Q4_4,Q4_5,Q4_6,Q4_7,Q5_1,Q5_2,Q5_3,Q5_4,Q5_5,Q5_6,Q5_7,Q6,Q7,Q8,Q9,Q10
1,2021-05-20 16:40:55,2021-05-20 16:43:24,IP Address,49.180.248.16,100,149,True,2021-05-20 16:43:24.837000,R_1BNLvUyfQrs0zoR,NaN,NaN,NaN,NaN,-33.856293,151.212189,anonymous,EN,7,8,1 - Extremely Disagree,9,1 - Extremely Disagree,3,5 - I'm not sure,8,5 - I'm not sure,8,6,9,7,9,3,5 - I'm not sure,5 - I'm not sure,3,5 - I'm not sure,6,3,7,4,8,7,9,6,5 - I'm not sure,Female,18-25,Postgraduate,"Below $18,000",No
2,2021-05-20 16:57:30,2021-05-20 16:58:58,IP Address,43.225.62.66,100,88,True,2021-05-20 16:58:58.913000,R_241pEiX5GGbjl2Q,NaN,NaN,NaN,NaN,-35.269699,149.137512,anonymous,EN,6,7,8,9,8,8,10 - Extremely Agree,10 - Extremely Agree,5 - I'm not sure,7,4,6,8,8,1 - Extremely Disagree,1 - Extremely Disagree,3,1 - Extremely Disagree,4,4,3,8,3,3,6,7,9,8,Male,36-45,Postgraduate,"Above $110,000",Yes
3,2021-05-20 17:02:42,2021-05-20 17:05:56,IP Address,103.192.227.226,100,193,True,2021-05-20 17:05:56.532000,R_12S8jTeh77IdKY5,NaN,NaN,NaN,NaN,22.257797,114.16571,anonymous,EN,4,8,3,8,1 - Extremely Disagree,5 - I'm not sure,5 - I'm not sure,6,8,9,8,9,5 - I'm not sure,8,3,6,8,6,8,5 - I'm not sure,6,5 - I'm not sure,6,7,7,8,5 - I'm not sure,7,Female,26-35,Undergraduate,"$30,000-$50,000",Yes
4,2021-05-20 17:04:25,2021-05-20 17:06:15,IP Address,1.159.46.246,100,109,True,2021-05-20 17:06:15.260000,R_5szq28NGXKsyryp,NaN,NaN,NaN,NaN,-37.908798,144.9953,anonymous,EN,4,9,7,6,9,6,9,6,5 - I'm not sure,5 - I'm not sure,3,7,8,7,3,4,4,6,7,7,2,9,4,4,5 - I'm not sure,6,7,6,Male,36-45,TAFE,"Above $110,000",Yes
5,2021-05-20 17:16:15,2021-05-20 17:18:50,IP Address,117.20.69.225,100,154,True,2021-05-20 17:18:50.476000,R_2wo7R1waDZlX7I4,NaN,NaN,NaN,NaN,-27.473206,153.021515,anonymous,EN,3,10 - Extremely Agree,9,8,10 - Extremely Agree,8,10 - Extremely Agree,7,6,5 - I'm not sure,8,8,8,8,3,9,7,6,8,9,7,8,7,5 - I'm not sure,6,6,7,4,Female,46-60,TAFE,"Above $110,000",Yes

In [5]:
data['Q1_1'].value_counts()

5 - I'm not sure          7
1 - Extremely Disagree    5
4                         5
3                         5
7                         5
6                         5
8                         4
10 - Extremely Agree      3
9                         1
2                         1
Name: Q1_1, dtype: int64

In [6]:
data.columns.get_loc('Q1_1')

17

In [7]:
data.columns.get_loc('Q5_7')

44

In [11]:
survey_data = data.iloc[:, 17:45]
survey_data.head()

,Q1_1,Q1_2,Q1_3,Q1_4,Q1_5,Q1_6,Q1_7,Q3_1,Q3_2,Q3_3,Q3_4,Q3_5,Q3_6,Q3_7,Q4_1,Q4_2,Q4_3,Q4_4,Q4_5,Q4_6,Q4_7,Q5_1,Q5_2,Q5_3,Q5_4,Q5_5,Q5_6,Q5_7
1,7,8,1 - Extremely Disagree,9,1 - Extremely Disagree,3,5 - I'm not sure,8,5 - I'm not sure,8,6,9,7,9,3,5 - I'm not sure,5 - I'm not sure,3,5 - I'm not sure,6,3,7,4,8,7,9,6,5 - I'm not sure
2,6,7,8,9,8,8,10 - Extremely Agree,10 - Extremely Agree,5 - I'm not sure,7,4,6,8,8,1 - Extremely Disagree,1 - Extremely Disagree,3,1 - Extremely Disagree,4,4,3,8,3,3,6,7,9,8
3,4,8,3,8,1 - Extremely Disagree,5 - I'm not sure,5 - I'm not sure,6,8,9,8,9,5 - I'm not sure,8,3,6,8,6,8,5 - I'm not sure,6,5 - I'm not sure,6,7,7,8,5 - I'm not sure,7
4,4,9,7,6,9,6,9,6,5 - I'm not sure,5 - I'm not sure,3,7,8,7,3,4,4,6,7,7,2,9,4,4,5 - I'm not sure,6,7,6
5,3,10 - Extremely Agree,9,8,10 - Extremely Agree,8,10 - Extremely Agree,7,6,5 - I'm not sure,8,8,8,8,3,9,7,6,8,9,7,8,7,5 - I'm not sure,6,6,7,4

In [15]:
for i in survey_data.columns:
    survey_data[i] = survey_data[i].apply(lambda x: 1 if x == '1 - Extremely Disagree'
                                            else 5 if x == "5 - I'm not sure"
                                            else 10 if x == '10 - Extremely Agree'
                                            else x)
survey_data.head()

<ipython-input-15-85b6116980ac>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  survey_data[i] = survey_data[i].apply(lambda x: 1 if x == '1 - Extremely Disagree'

,Q1_1,Q1_2,Q1_3,Q1_4,Q1_5,Q1_6,Q1_7,Q3_1,Q3_2,Q3_3,Q3_4,Q3_5,Q3_6,Q3_7,Q4_1,Q4_2,Q4_3,Q4_4,Q4_5,Q4_6,Q4_7,Q5_1,Q5_2,Q5_3,Q5_4,Q5_5,Q5_6,Q5_7
1,7,8,1,9,1,3,5,8,5,8,6,9,7,9,3,5,5,3,5,6,3,7,4,8,7,9,6,5
2,6,7,8,9,8,8,10,10,5,7,4,6,8,8,1,1,3,1,4,4,3,8,3,3,6,7,9,8
3,4,8,3,8,1,5,5,6,8,9,8,9,5,8,3,6,8,6,8,5,6,5,6,7,7,8,5,7
4,4,9,7,6,9,6,9,6,5,5,3,7,8,7,3,4,4,6,7,7,2,9,4,4,5,6,7,6
5,3,10,9,8,10,8,10,7,6,5,8,8,8,8,3,9,7,6,8,9,7,8,7,5,6,6,7,4

In [17]:
survey_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41 entries, 1 to 41
Data columns (total 28 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Q1_1    41 non-null     object
 1   Q1_2    41 non-null     object
 2   Q1_3    41 non-null     object
 3   Q1_4    41 non-null     object
 4   Q1_5    41 non-null     object
 5   Q1_6    41 non-null     object
 6   Q1_7    41 non-null     object
 7   Q3_1    41 non-null     object
 8   Q3_2    41 non-null     object
 9   Q3_3    41 non-null     object
 10  Q3_4    41 non-null     object
 11  Q3_5    41 non-null     object
 12  Q3_6    41 non-null     object
 13  Q3_7    41 non-null     object
 14  Q4_1    41 non-null     object
 15  Q4_2    41 non-null     object
 16  Q4_3    41 non-null     object
 17  Q4_4    41 non-null     object
 18  Q4_5    41 non-null     object
 19  Q4_6    41 non-null     object
 20  Q4_7    41 non-null     object
 21  Q5_1    41 non-null     object
 22  Q5_2    41 non-null     object
 23  Q5_3    41 non-null     object
 24  Q5_4    41 non-null     object
 25  Q5_5    41 non-null     object
 26  Q5_6    41 non-null     object
 27  Q5_7    41 non-null     object
dtypes: object(28)
memory usage: 9.3+ KB

In [21]:
for i in survey_data.columns:
    survey_data[i] = survey_data[i].astype('int')

survey_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41 entries, 1 to 41
Data columns (total 28 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Q1_1    41 non-null     int32
 1   Q1_2    41 non-null     int32
 2   Q1_3    41 non-null     int32
 3   Q1_4    41 non-null     int32
 4   Q1_5    41 non-null     int32
 5   Q1_6    41 non-null     int32
 6   Q1_7    41 non-null     int32
 7   Q3_1    41 non-null     int32
 8   Q3_2    41 non-null     int32
 9   Q3_3    41 non-null     int32
 10  Q3_4    41 non-null     int32
 11  Q3_5    41 non-null     int32
 12  Q3_6    41 non-null     int32
 13  Q3_7    41 non-null     int32
 14  Q4_1    41 non-null     int32
 15  Q4_2    41 non-null     int32
 16  Q4_3    41 non-null     int32
 17  Q4_4    41 non-null     int32
 18  Q4_5    41 non-null     int32
 19  Q4_6    41 non-null     int32
 20  Q4_7    41 non-null     int32
 21  Q5_1    41 non-null     int32
 22  Q5_2    41 non-null     int32
 23  Q5_3    41 non-null     int32
 24  Q5_4    41 non-null     int32
 25  Q5_5    41 non-null     int32
 26  Q5_6    41 non-null     int32
 27  Q5_7    41 non-null     int32
dtypes: int32(28)
memory usage: 4.8 KB

<ipython-input-21-3a6daab0e377>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  survey_data[i] = survey_data[i].astype('int')

In [24]:
survey_data_normalized = survey_data.copy()

for i in survey_data_normalized.columns:
    survey_data_normalized[i] = survey_data_normalized[i].apply(lambda x: x-5)
    
survey_data_normalized.head()

,Q1_1,Q1_2,Q1_3,Q1_4,Q1_5,Q1_6,Q1_7,Q3_1,Q3_2,Q3_3,Q3_4,Q3_5,Q3_6,Q3_7,Q4_1,Q4_2,Q4_3,Q4_4,Q4_5,Q4_6,Q4_7,Q5_1,Q5_2,Q5_3,Q5_4,Q5_5,Q5_6,Q5_7
1,2,3,-4,4,-4,-2,0,3,0,3,1,4,2,4,-2,0,0,-2,0,1,-2,2,-1,3,2,4,1,0
2,1,2,3,4,3,3,5,5,0,2,-1,1,3,3,-4,-4,-2,-4,-1,-1,-2,3,-2,-2,1,2,4,3
3,-1,3,-2,3,-4,0,0,1,3,4,3,4,0,3,-2,1,3,1,3,0,1,0,1,2,2,3,0,2
4,-1,4,2,1,4,1,4,1,0,0,-2,2,3,2,-2,-1,-1,1,2,2,-3,4,-1,-1,0,1,2,1
5,-2,5,4,3,5,3,5,2,1,0,3,3,3,3,-2,4,2,1,3,4,2,3,2,0,1,1,2,-1

In [25]:
# survey_data_normalized['Q1_F1'] = survey_data_normalized[['Q1_3', 'Q1_5', 'Q1_6', 'Q1_7']].mean(axis=1)
# survey_data_normalized['Q1_F2'] = survey_data_normalized[['Q1_2', 'Q1_4', 'Q1_6']].mean(axis=1)

# survey_data_normalized['Q2_F1'] = survey_data_normalized[['Q3_3', 'Q3_5', 'Q3_6', 'Q3_7']].mean(axis=1)
# survey_data_normalized['Q2_F2'] = survey_data_normalized[['Q3_2', 'Q3_4', 'Q3_6']].mean(axis=1)

# survey_data_normalized['Q3_F1'] = survey_data_normalized[['Q4_3', 'Q4_5', 'Q4_6', 'Q4_7']].mean(axis=1)
# survey_data_normalized['Q3_F2'] = survey_data_normalized[['Q4_2', 'Q4_4', 'Q4_6']].mean(axis=1)

# survey_data_normalized['Q4_F1'] = survey_data_normalized[['Q5_3', 'Q5_5', 'Q5_6', 'Q5_7']].mean(axis=1)
# survey_data_normalized['Q4_F2'] = survey_data_normalized[['Q5_2', 'Q5_4', 'Q5_6']].mean(axis=1)

# survey_data_normalized.head()

,Q1_1,Q1_2,Q1_3,Q1_4,Q1_5,Q1_6,Q1_7,Q3_1,Q3_2,Q3_3,Q3_4,Q3_5,Q3_6,Q3_7,Q4_1,Q4_2,Q4_3,Q4_4,Q4_5,Q4_6,Q4_7,Q5_1,Q5_2,Q5_3,Q5_4,Q5_5,Q5_6,Q5_7,Q1_F1,Q1_F2,Q2_F1,Q2_F2,Q3_F1,Q3_F2,Q4_F1,Q4_F2
1,2,3,-4,4,-4,-2,0,3,0,3,1,4,2,4,-2,0,0,-2,0,1,-2,2,-1,3,2,4,1,0,-2.50,1.666667,3.25,1.000000,-0.25,-0.333333,2.00,0.666667
2,1,2,3,4,3,3,5,5,0,2,-1,1,3,3,-4,-4,-2,-4,-1,-1,-2,3,-2,-2,1,2,4,3,3.50,3.000000,2.25,0.666667,-1.50,-3.000000,1.75,1.000000
3,-1,3,-2,3,-4,0,0,1,3,4,3,4,0,3,-2,1,3,1,3,0,1,0,1,2,2,3,0,2,-1.50,2.000000,2.75,2.000000,1.75,0.666667,1.75,1.000000
4,-1,4,2,1,4,1,4,1,0,0,-2,2,3,2,-2,-1,-1,1,2,2,-3,4,-1,-1,0,1,2,1,2.75,2.000000,1.75,0.333333,0.00,0.666667,0.75,0.333333
5,-2,5,4,3,5,3,5,2,1,0,3,3,3,3,-2,4,2,1,3,4,2,3,2,0,1,1,2,-1,4.25,3.666667,2.25,2.333333,2.75,3.000000,0.50,1.666667

In [28]:
# 加权平均
survey_data_normalized['Q1_F1'] = 0.457*survey_data_normalized['Q1_3'] + 0.957*survey_data_normalized['Q1_5'] + 0.528*survey_data_normalized['Q1_6'] + 0.503*survey_data_normalized['Q1_7']
survey_data_normalized['Q1_F2'] = 0.555*survey_data_normalized['Q1_2'] + 1.042*survey_data_normalized['Q1_4'] + 0.402*survey_data_normalized['Q1_6']

survey_data_normalized['Q2_F1'] = 0.457*survey_data_normalized['Q3_3'] + 0.957*survey_data_normalized['Q3_5'] + 0.528*survey_data_normalized['Q3_6'] + 0.503*survey_data_normalized['Q3_7']
survey_data_normalized['Q2_F2'] = 0.555*survey_data_normalized['Q3_2'] + 1.042*survey_data_normalized['Q3_4'] + 0.402*survey_data_normalized['Q3_6']

survey_data_normalized['Q3_F1'] = 0.457*survey_data_normalized['Q4_3'] + 0.957*survey_data_normalized['Q4_5'] + 0.528*survey_data_normalized['Q4_6'] + 0.503*survey_data_normalized['Q4_7']
survey_data_normalized['Q3_F2'] = 0.555*survey_data_normalized['Q4_2'] + 1.042*survey_data_normalized['Q4_4'] + 0.402*survey_data_normalized['Q4_6']

survey_data_normalized['Q4_F1'] = 0.457*survey_data_normalized['Q5_3'] + 0.957*survey_data_normalized['Q5_5'] + 0.528*survey_data_normalized['Q5_6'] + 0.503*survey_data_normalized['Q5_7']
survey_data_normalized['Q4_F2'] = 0.555*survey_data_normalized['Q5_2'] + 1.042*survey_data_normalized['Q5_4'] + 0.402*survey_data_normalized['Q5_6']

survey_data_normalized.head()

,Q1_1,Q1_2,Q1_3,Q1_4,Q1_5,Q1_6,Q1_7,Q3_1,Q3_2,Q3_3,Q3_4,Q3_5,Q3_6,Q3_7,Q4_1,Q4_2,Q4_3,Q4_4,Q4_5,Q4_6,Q4_7,Q5_1,Q5_2,Q5_3,Q5_4,Q5_5,Q5_6,Q5_7,Q1_F1,Q1_F2,Q2_F1,Q2_F2,Q3_F1,Q3_F2,Q4_F1,Q4_F2
1,2,3,-4,4,-4,-2,0,3,0,3,1,4,2,4,-2,0,0,-2,0,1,-2,2,-1,3,2,4,1,0,-6.712,5.029,8.267,1.846,-0.478,-1.682,5.727,1.931
2,1,2,3,4,3,3,5,5,0,2,-1,1,3,3,-4,-4,-2,-4,-1,-1,-2,3,-2,-2,1,2,4,3,8.341,6.484,4.964,0.164,-3.405,-6.790,4.621,1.540
3,-1,3,-2,3,-4,0,0,1,3,4,3,4,0,3,-2,1,3,1,3,0,1,0,1,2,2,3,0,2,-4.742,4.791,7.165,4.791,4.745,1.597,4.791,2.639
4,-1,4,2,1,4,1,4,1,0,0,-2,2,3,2,-2,-1,-1,1,2,2,-3,4,-1,-1,0,1,2,1,7.282,3.664,4.504,-0.878,1.004,1.291,2.059,0.249
5,-2,5,4,3,5,3,5,2,1,0,3,3,3,3,-2,4,2,1,3,4,2,3,2,0,1,1,2,-1,10.712,7.107,5.964,4.887,6.903,4.870,1.510,2.956

In [29]:
Q1_F1 = survey_data_normalized['Q1_F1'].mean()
Q1_F2 = survey_data_normalized['Q1_F2'].mean()

Q2_F1 = survey_data_normalized['Q2_F1'].mean()
Q2_F2 = survey_data_normalized['Q2_F2'].mean()

Q3_F1 = survey_data_normalized['Q3_F1'].mean()
Q3_F2 = survey_data_normalized['Q3_F2'].mean()

Q4_F1 = survey_data_normalized['Q4_F1'].mean()
Q4_F2 = survey_data_normalized['Q4_F2'].mean()

In [30]:
df = pd.DataFrame({"Car": ['Tesla', 'BMW', 'Hyundai', 'Audi'],
                                         "F1": [Q1_F1, Q2_F1, Q3_F1, Q4_F1],
                                         "F2": [Q1_F2, Q2_F2, Q3_F2, Q4_F2]})
df

       Car        F1        F2
0    Tesla  1.055073  3.907805
1      BMW  5.569951  2.142659
2  Hyundai  1.695171 -0.064878
3     Audi  4.517439  2.974902

# Perceptual Map

In [40]:
import plotly.express as px

fig = px.scatter(df, x="F1", y="F2", hover_name="Car", text='Car',
                labels=dict(F1="Moderate Performance vs High Performance", F2="Traditional vs Technology Driven"))

fig.update_xaxes(range=[-6,6])
fig.update_yaxes(range=[-6,6])
fig.update_traces(textposition='top center')

fig.update_layout(
    title = {
        'text': "Perceptual Map",
      # 'y':0.9,
        'x':0.5,
        'xanchor': 'center',
        'yanchor': 'top'}
)

fig.show()